### PR TITLE
Fixed an issue with the URL in the settings tabs

### LINKED ISSUE #121: Update settings tabs to use admin_url() instead of just query string params
https://wordpress.org/support/topic/bug-after-saving-settings-tab-navigation-breaks/

### PR DESCRIPTION
**Pull request by petenelson**
Closes #121

### CODE REVIEW

File: includes/settings/class-wp-rest-api-log-settings.php [hunk 1]
```diff
@@ -109,16 +109,37 @@ static private function current_tab() {
...
+		/**
+		 * Outputs the HTML for the settings tabs.
+		 *
+		 * @return void
+		 */
 		static private function plugin_options_tabs() {
 			$current_tab = self::current_tab();
 
-			echo '<h2>' . __( 'Settings' ) . ' &rsaquo; REST API Log</h2><h2 class="nav-tab-wrapper">';
+			echo '<h2>' . esc_html__( 'Settings' ) . ' &rsaquo; REST API Log</h2><h2 class="nav-tab-wrapper">';
```
Comment (bswatson) [inline includes/settings/class-wp-rest-api-log-settings.php]: No translation strings?

Comment (petenelson) [inline includes/settings/class-wp-rest-api-log-settings.php]: Not for something that would already be included with core

Comment (ericmann) [inline includes/settings/class-wp-rest-api-log-settings.php]: What about for "REST API Log"?

Comment (petenelson) [inline includes/settings/class-wp-rest-api-log-settings.php]: More of a toss-up, since it's the proper name of the plugin, and an acronym.  We'll cross that bridge when someone wants to do translations.
